### ISSUE TITLE
Server executable doesn't work on Mono/eddyn

### ISSUE THREAD

**Issue by cornfields74** [yeti0904/MCYeti#7]
Currently, MCYeti doesn't support Mono, when I tried to launch MCYeti through Mono (via eddynet) it gave me an error that the executable does not contain a valid CIL image
![image](https://github.com/yeti0904/MCYeti/assets/131550775/e061cacd-f558-4176-a604-a3d04a74a756)

**Comment by MESYETI** [comment]
it's not possible for mono to run MCYeti because MCYeti isn't made in a .NET language
